name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.2.1
      - name: check format
        run: deno fmt --check

      - name: test oakCors examples
        run: ./test/run.sh oak

      - name: test opineCors examples
        run: ./test/run.sh opine

      - name: test abcCors examples
        run: ./test/run.sh abc

      - name: test attainCors examples
        run: ./test/run.sh attain

      # - name: test mithCors examples
      #   run: ./test/run.sh mith
